// Package send validates a handoff draft and enqueues it into the sender's
// outbox. It ports swarm_handoff.bb.
package send

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/dudehook/swarmforge/internal/handoff"
	"github.com/dudehook/swarmforge/internal/project"
)

const usageText = `Usage: swarm_handoff.sh <draft-file>

Draft formats:

type: git_handoff
to: <role>[,<role>...]
priority: NN
task: <short-stable-task-name>
commit: <10-char-commit-abbrev>

type: note
to: <role>[,<role>...]
priority: NN
message: <one line, max 80 chars>`

var (
	reservedFields = map[string]bool{
		"id": true, "from": true, "role": true, "recipient": true,
		"created_at": true, "enqueued_at": true, "dequeued_at": true, "completed_at": true,
	}
	allowedFields = map[string]bool{
		"type": true, "to": true, "priority": true, "task": true, "commit": true, "message": true,
	}
	allowedTypes = map[string]bool{"git_handoff": true, "note": true}

	priorityRe = regexp.MustCompile(`^[0-9][0-9]$`)
	commitRe   = regexp.MustCompile(`^[0-9a-fA-F]{10}$`)
)

// UsageError is returned when invocation is malformed (wrong arg count).
type UsageError struct{}

func (UsageError) Error() string { return usageText }

type parsed struct {
	headers map[string]string
	ordered []string
	errors  []string
}

// Send validates the draft at draftPath and, if valid, writes the handoff into
// the sender's outbox and deletes the draft. workDir is the process working
// directory; root is the resolved project root; sender is the sending role.
func Send(out io.Writer, workDir, root, sender, draftPath string) error {
	info, err := os.Stat(draftPath)
	if err != nil || info.IsDir() {
		return &handoff.ExitError{Code: 1, Message: "Draft file not found: " + draftPath}
	}
	if known, err := project.Known(root, sender); err != nil {
		return err
	} else if !known {
		return &handoff.ExitError{Code: 1, Message: "Unknown sender role: " + sender}
	}

	data, err := os.ReadFile(draftPath)
	if err != nil {
		return err
	}
	p := parseDraft(string(data))
	recipients, canonicalCommit, vErrors := validate(workDir, root, p.headers, p.ordered)

	allErrors := append(append([]string{}, p.errors...), vErrors...)
	if len(allErrors) > 0 {
		return &handoff.ExitError{Code: 2, Message: errorReport(draftPath, allErrors)}
	}

	outboxFile, err := writeHandoff(workDir, sender, p.headers, recipients, canonicalCommit)
	if err != nil {
		return err
	}
	if err := os.Remove(draftPath); err != nil {
		return err
	}
	fmt.Fprintf(out, "HANDOFF QUEUED: %s\n", outboxFile)
	return nil
}

func parseDraft(content string) parsed {
	headers := map[string]string{}
	var ordered []string
	var errs []string
	bodySeen := false

	for i, line := range handoff.SplitLines(content) {
		lineNo := i + 1
		switch {
		case bodySeen:
			if strings.TrimSpace(line) != "" {
				errs = append(errs, fmt.Sprintf("Line %d: draft handoffs may contain headers only; payloads are generated by swarm_handoff.sh.", lineNo))
			}
		case strings.TrimSpace(line) == "":
			bodySeen = true
		case !strings.Contains(line, ": "):
			errs = append(errs, fmt.Sprintf("Line %d: expected 'field: value'.", lineNo))
		default:
			parts := strings.SplitN(line, ": ", 2)
			field, value := parts[0], parts[1]
			switch {
			case strings.TrimSpace(field) == "" || strings.TrimSpace(value) == "":
				errs = append(errs, fmt.Sprintf("Line %d: field and value must both be non-empty.", lineNo))
			case reservedFields[field]:
				errs = append(errs, fmt.Sprintf("Line %d: header '%s' is reserved and must not be written by agents.", lineNo, field))
			case !allowedFields[field]:
				errs = append(errs, fmt.Sprintf("Line %d: unknown header '%s'.", lineNo, field))
			case contains(headers, field):
				errs = append(errs, fmt.Sprintf("Line %d: duplicate header '%s'.", lineNo, field))
			default:
				headers[field] = value
				ordered = append(ordered, field)
			}
		}
	}
	return parsed{headers: headers, ordered: ordered, errors: errs}
}

func validate(workDir, root string, headers map[string]string, ordered []string) (recipients []string, canonicalCommit string, errs []string) {
	typ := headers["type"]
	to := headers["to"]
	priority := headers["priority"]
	commit := headers["commit"]
	taskName := headers["task"]
	noteMessage := headers["message"]

	recipients, recipientErrors := validateRecipients(root, to)

	var fieldErrors []string
	if typ != "" {
		for _, field := range ordered {
			if !allowedForType(typ, field) {
				fieldErrors = append(fieldErrors, fmt.Sprintf("Header '%s' is not allowed for type '%s'.", field, typ))
			}
		}
	}

	var baseErrors []string
	if strings.TrimSpace(typ) == "" {
		baseErrors = append(baseErrors, "Missing required header 'type'.")
	}
	if strings.TrimSpace(to) == "" {
		baseErrors = append(baseErrors, "Missing required header 'to'.")
	}
	if strings.TrimSpace(priority) == "" {
		baseErrors = append(baseErrors, "Missing required header 'priority'.")
	}
	if strings.TrimSpace(typ) != "" && !allowedTypes[typ] {
		baseErrors = append(baseErrors, fmt.Sprintf("Header 'type' must be one of git_handoff or note; got '%s'.", typ))
	}
	if strings.TrimSpace(priority) != "" && !priorityRe.MatchString(priority) {
		baseErrors = append(baseErrors, fmt.Sprintf("Header 'priority' must be two digits from 00 to 99; got '%s'.", priority))
	}

	var commitError string
	if typ == "git_handoff" {
		switch {
		case strings.TrimSpace(commit) == "":
			commitError = "Missing required header 'commit' for git_handoff."
		case !commitRe.MatchString(commit):
			commitError = fmt.Sprintf("Header 'commit' must be exactly 10 hexadecimal characters; got '%s'.", commit)
		default:
			canonicalCommit, commitError = canonicalCommitFor(workDir, commit)
		}
	}

	var gitErrors []string
	if typ == "git_handoff" {
		if strings.TrimSpace(taskName) == "" {
			gitErrors = append(gitErrors, "Missing required header 'task' for git_handoff.")
		} else if len(taskName) > 80 {
			gitErrors = append(gitErrors, fmt.Sprintf("Header 'task' must be no longer than 80 characters; got %d.", len(taskName)))
		}
	} else {
		if strings.TrimSpace(commit) != "" {
			gitErrors = append(gitErrors, "Header 'commit' is only allowed for git_handoff.")
		}
		if strings.TrimSpace(taskName) != "" {
			gitErrors = append(gitErrors, "Header 'task' is only allowed for git_handoff.")
		}
	}
	if commitError != "" {
		gitErrors = append(gitErrors, commitError)
	}

	var noteErrors []string
	if typ == "note" {
		if strings.TrimSpace(noteMessage) == "" {
			noteErrors = append(noteErrors, "Missing required header 'message' for note.")
		} else if len(noteMessage) > 80 {
			noteErrors = append(noteErrors, fmt.Sprintf("Header 'message' must be no longer than 80 characters; got %d.", len(noteMessage)))
		}
	} else if strings.TrimSpace(noteMessage) != "" {
		noteErrors = append(noteErrors, "Header 'message' is only allowed for note.")
	}

	errs = concat(baseErrors, recipientErrors, fieldErrors, gitErrors, noteErrors)
	return recipients, canonicalCommit, errs
}

func validateRecipients(root, to string) (recipients []string, errs []string) {
	if strings.TrimSpace(to) == "" {
		return nil, nil
	}
	recipients = strings.Split(to, ",")
	seen := map[string]bool{}
	for _, recipient := range recipients {
		if strings.TrimSpace(recipient) == "" {
			errs = append(errs, "Header 'to' contains an empty recipient.")
		}
		if strings.Contains(recipient, "_") {
			errs = append(errs, fmt.Sprintf("Recipient role '%s' is invalid; role names may not contain underscores.", recipient))
		}
		if seen[recipient] {
			errs = append(errs, fmt.Sprintf("Duplicate recipient '%s'.", recipient))
		}
		if strings.TrimSpace(recipient) != "" {
			if known, err := project.Known(root, recipient); err == nil && !known {
				errs = append(errs, fmt.Sprintf("Unknown recipient role '%s'.", recipient))
			}
		}
		seen[recipient] = true
	}
	return recipients, errs
}

func allowedForType(typ, field string) bool {
	switch typ {
	case "git_handoff":
		switch field {
		case "type", "to", "priority", "task", "commit":
			return true
		}
	case "note":
		switch field {
		case "type", "to", "priority", "message":
			return true
		}
	}
	return false
}

// canonicalCommitFor resolves commit to a single 10-char commit abbreviation,
// returning an error message if it is ambiguous or not a commit.
func canonicalCommitFor(workDir, commit string) (canonical string, errMsg string) {
	matchesOut := gitOut(workDir, "rev-parse", "--disambiguate="+commit)
	matches := nonEmptyLines(matchesOut)
	if len(matches) != 1 {
		return "", fmt.Sprintf("Header 'commit' must resolve to exactly one Git object; '%s' matched %d.", commit, len(matches))
	}
	object := matches[0]
	objectType := strings.TrimSpace(gitOut(workDir, "cat-file", "-t", object))
	if objectType != "commit" {
		return "", fmt.Sprintf("Header 'commit' must resolve to a commit; '%s' resolves to '%s'.", commit, objectType)
	}
	return strings.TrimSpace(gitOut(workDir, "rev-parse", "--short=10", object)), ""
}

func writeHandoff(workDir, sender string, headers map[string]string, recipients []string, canonicalCommit string) (string, error) {
	timestampID := handoff.IDTimestamp()
	createdAt := handoff.Timestamp()
	sequence, err := handoff.NextSequence(workDir)
	if err != nil {
		return "", err
	}
	id := timestampID + "_" + sequence + "_from_" + sender
	recipientSlug := strings.Join(recipients, "_")
	priority := headers["priority"]
	typ := headers["type"]
	filename := priority + "_" + timestampID + "_" + sequence + "_from_" + sender + "_to_" + recipientSlug + ".handoff"

	stateDir := handoff.StateDir(workDir)
	outboxDir := filepath.Join(stateDir, "outbox")
	tmpDir := filepath.Join(outboxDir, "tmp")
	tmpFile := filepath.Join(tmpDir, filename+".tmp")
	outboxFile := filepath.Join(outboxDir, filename)

	lines := []string{
		"id: " + id,
		"from: " + sender,
		"to: " + strings.Join(recipients, ","),
		"priority: " + priority,
		"type: " + typ,
	}
	switch typ {
	case "git_handoff":
		lines = append(lines,
			"role: "+sender,
			"task: "+headers["task"],
			"commit: "+canonicalCommit)
	case "note":
		lines = append(lines, "message: "+headers["message"])
	}
	lines = append(lines, "created_at: "+createdAt, "", bodyFor(typ, sender, canonicalCommit, headers["message"]))

	for _, dir := range []string{tmpDir, outboxDir, filepath.Join(stateDir, "sent"), filepath.Join(stateDir, "failed")} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", err
		}
	}
	if err := os.WriteFile(tmpFile, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmpFile, outboxFile); err != nil {
		return "", err
	}
	return outboxFile, nil
}

func bodyFor(typ, sender, canonicalCommit, message string) string {
	switch typ {
	case "git_handoff":
		return "Re-read your role and constitution.\n\nmerge_and_process " + sender + " " + canonicalCommit
	case "note":
		return "Re-read your role and constitution.\n\n" + message
	}
	return ""
}

func errorReport(draft string, errors []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "HANDOFF INVALID: %s\n\nErrors:\n", draft)
	for _, e := range errors {
		fmt.Fprintf(&b, "- %s\n", e)
	}
	fmt.Fprintf(&b, "\n%s", usageText)
	return b.String()
}

func gitOut(dir string, args ...string) string {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, _ := cmd.Output()
	return string(out)
}

func nonEmptyLines(s string) []string {
	var out []string
	for _, line := range strings.Split(s, "\n") {
		if strings.TrimSpace(line) != "" {
			out = append(out, strings.TrimSpace(line))
		}
	}
	return out
}

func contains(m map[string]string, key string) bool {
	_, ok := m[key]
	return ok
}

func concat(slices ...[]string) []string {
	var out []string
	for _, s := range slices {
		out = append(out, s...)
	}
	return out
}
